import { RegisterClientOptions } from '@peertube/peertube-types/client'

export async function register (options: RegisterClientOptions) {
  const { peertubeHelpers, registerHook, registerVideoField } = options

  // 1. Register custom fields in video upload/edit form IMMEDIATELY (synchronously)
  // This must happen before any await to avoid race conditions with PeerTube's form rendering
  if (typeof registerVideoField === 'function') {
      const modeField = {
        name: 'tessera-mode',
        label: 'Tessera Monetization Mode',
        descriptionHTML: 'Choose how viewers pay for this video.',
        type: 'select' as const,
        options: [
            { value: 'pay-per-second', label: '⚡ Pay-per-second' },
            { value: 'tips', label: '💝 Tips (free to watch)' },
        ],
        default: 'pay-per-second'
      }
      registerVideoField(modeField, { type: 'upload' })
      registerVideoField(modeField, { type: 'update' })

      const rateField = {
        name: 'tessera-rate',
        label: 'Rate per second (USDC)',
        type: 'input' as const,
        default: '0.0001',
        descriptionHTML: 'Only applies to pay-per-second mode.'
      }
      registerVideoField(rateField, { type: 'upload' })
      registerVideoField(rateField, { type: 'update' })
  }

  // 2. Fetch Tessera Base URL from plugin router
  let baseUrl: string
  try {
    const pluginRoute = peertubeHelpers.getBaseRouterRoute()
    const response = await fetch(`${pluginRoute}/base-url`)
    const data = await response.json()
    if (data.baseUrl) {
      baseUrl = data.baseUrl
    } else {
      console.warn('[tessera] Missing base URL configuration.')
      return
    }
  } catch (err) {
    console.error('[tessera] Failed to fetch base URL:', err)
    return
  }

  // Inject SPA styles to prevent paywall from blocking the dashboard
  const style = document.createElement('style')
  style.innerHTML = `
    body.arc-hide-paywall {
       overflow: auto !important;
    }
    body.arc-hide-paywall #arc-paywall-overlay,
    body.arc-hide-paywall #arc-session-manager {
       display: none !important;
    }
    body.arc-locked.arc-hide-paywall > * {
       filter: none !important;
       pointer-events: auto !important;
       user-select: auto !important;
    }
  `
  document.head.appendChild(style)

  const checkPageVisibility = () => {
      const isWatchPage = window.location.pathname.includes('/watch') || window.location.pathname.includes('/w/')
      if (!isWatchPage) {
         document.body.classList.add('arc-hide-paywall')
      } else {
         document.body.classList.remove('arc-hide-paywall')
      }
  }
  // Run immediately to prevent modal flicker
  checkPageVisibility()

  // 3. Inject Tessera paywall assets dynamically
  const cssLink = document.createElement('link')
  cssLink.rel = 'stylesheet'
  cssLink.href = `${baseUrl}/peertube-assets/paywall.css`
  document.head.appendChild(cssLink)

  const script = document.createElement('script')
  script.src = `${baseUrl}/peertube-assets/paywall.bundle.js`
  document.head.appendChild(script)

  // 4. Helper to get videoId from URL
  let currentVideoId: string | null = null

  registerHook({
    target: 'action:video-watch.video.loaded',
    handler: (params: any) => {
      if (params && params.video) {
        currentVideoId = params.video.uuid || params.video.id?.toString() || null
      }
    }
  })

  function getCurrentVideoId(): string | null {
    return currentVideoId
  }

  // Helper: read the sessionId generated by paywall.js (stored in localStorage)
  // This must match the userId the paywall sends to /register-session in Tessera.
  const getPaywallUserId = (): string | null => {
      try {
          return localStorage.getItem('arc_cashier_user_id')
      } catch {
          return null
      }
  }

  const isPaywallUnlocked = (): boolean => {
      try { return !document.body.classList.contains('arc-locked') }
      catch { return false }
  }

  // 4. Ping Mechanism
  const PING_INTERVAL_MS = 15000 // 15 seconds
  let pingInterval: number | undefined
  let abortController: AbortController | null = null
  let pendingPing: Promise<any> | null = null

  const sendPing = async (action: 'start' | 'stop' | 'ping'): Promise<void> => {
      if (action !== 'stop' && !isPaywallUnlocked()) return

      const videoId = getCurrentVideoId()
      const videoUrl = window.location.href
      const sessionId = getPaywallUserId()

      // Do not ping if the paywall has not yet generated a session ID.
      // The paywall.js creates arc_cashier_user_id in localStorage on init.
      if (!sessionId) {
          return
      }

      if (pendingPing) {
          try { await pendingPing } catch { /* ignore */ }
      }

      pendingPing = (async () => {
          try {
              const pluginRoute = peertubeHelpers.getBaseRouterRoute()
              const response = await fetch(`${pluginRoute}/ping`, {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({ action, videoId, videoUrl, sessionId })
              })
              if (!response.ok) {
                  if (response.status === 429) {
                      console.warn('[tessera] Rate limited. Skipping this ping.')
                  } else {
                      console.warn(`[tessera] Ping failed with status: ${response.status}`)
                  }
              } else {
                  const data = await response.json()
                  if (data.tesseraMode) {
                      document.body.setAttribute('data-tessera-mode', data.tesseraMode)
                  }
              }
          } catch (err) {
              console.error('[tessera] Failed to send ping:', err)
          } finally {
              pendingPing = null
          }
      })()

      await pendingPing
  }

  // 5. Hook into video player events for SPA navigation
  let currentVideo: HTMLVideoElement | null = null
  let isCleaningUp = false
  let hasStarted = false

  const cleanupVideoState = async () => {
      if (isCleaningUp) return
      isCleaningUp = true
      hasStarted = false
      if (pingInterval) {
          clearInterval(pingInterval)
          pingInterval = undefined
      }
      await sendPing('stop')
      if (abortController) {
          abortController.abort()
          abortController = null
      }
      currentVideo = null
      isCleaningUp = false
  }

  const attachVideoListeners = (video: HTMLVideoElement) => {
    console.log('[tessera] attachVideoListeners called for video:', video)
    if (abortController) {
        abortController.abort()
    }
    abortController = new AbortController()
    const { signal } = abortController

    // Take manual control over Tessera's visual paywall clock
    if (typeof window !== 'undefined') {
        (window as any).arcManualMediaControl = true;
    }

    // 4.1: Handle `play` event
    video.addEventListener('play', () => {
       console.log('[tessera] PLAY event detected. isPaywallUnlocked?', isPaywallUnlocked())
       if (hasStarted) return
       if (!isPaywallUnlocked()) return

       hasStarted = true
       if (typeof window !== 'undefined' && (window as any).arcSetMediaPlaying) {
           (window as any).arcSetMediaPlaying(true);
       }
       if (pingInterval) clearInterval(pingInterval)
       sendPing('start')
       pingInterval = window.setInterval(() => sendPing('ping'), PING_INTERVAL_MS)
    }, { signal })

    // 4.2: Handle `pause` and `ended` events
    video.addEventListener('pause', () => {
       console.log('[tessera] PAUSE event detected.')
       hasStarted = false
       if (typeof window !== 'undefined' && (window as any).arcSetMediaPlaying) {
           (window as any).arcSetMediaPlaying(false);
       }
       if (pingInterval) clearInterval(pingInterval)
       pingInterval = undefined
       sendPing('stop')
    }, { signal })

    video.addEventListener('ended', () => {
       console.log('[tessera] ENDED event detected.')
       hasStarted = false
       if (typeof window !== 'undefined' && (window as any).arcSetMediaPlaying) {
           (window as any).arcSetMediaPlaying(false);
       }
       if (pingInterval) clearInterval(pingInterval)
       pingInterval = undefined
       sendPing('stop')
    }, { signal })
  }

  // Fallback DOM polling to detect video element creation
  setInterval(async () => {
    checkPageVisibility()

    // Specifically target the main Video.js player to avoid grabbing thumbnail preview videos
    const video = document.querySelector('.vjs-tech, .video-js video, video-player video') as HTMLVideoElement | null
    
    // Video appeared or changed (User navigated to a new video page)
    if (video && video !== currentVideo) {
      console.log('[tessera] Found new video element:', video)
      
      // If we had a previous video playing, clean up its interval and stop billing
      if (currentVideo) {
         console.log('[tessera] Cleaning up previous video state.')
         await cleanupVideoState()
         return
      }

      currentVideo = video
      attachVideoListeners(video)
      
      // If video is already playing when we find it
      if (!video.paused && !video.ended) {
         console.log('[tessera] Video is already playing upon discovery! Sending start.')
         if (!hasStarted && isPaywallUnlocked()) {
             hasStarted = true
             if (pingInterval) clearInterval(pingInterval)
             sendPing('start')
             pingInterval = window.setInterval(() => sendPing('ping'), PING_INTERVAL_MS)
         }
      } else {
         console.log('[tessera] Video discovered in paused/ended state.')
      }
    }

    // Video disappeared (User navigated AWAY from video page to dashboard)
    if (!video && currentVideo) {
      await cleanupVideoState()
    }
  }, 1000)
}
